export const dashboardCurrencyOptions = [
  "$",
  "¥",
  "£",
  "€",
  "kr",
  "CHF",
  "R$",
  "Kč",
  "Ft",
  "Rp",
  "₩",
  "ƒ",
  "₽",
  "₱",
  "฿",
  "Rs",
  "MT",
  "zł",
];

export const timeZones = [
  ["Etc/GMT+0", "GMT 0"],
  ["Etc/GMT-1", "GMT +1"],
  ["Etc/GMT-2", "GMT+2"],
  ["Etc/GMT-3", "GMT+3"],
  ["Etc/GMT-4", "GMT+4"],
  ["Etc/GMT-5", "GMT+5"],
  ["Etc/GMT-6", "GMT+6"],
  ["Etc/GMT-7", "GMT+7"],
  ["Etc/GMT-8", "GMT+8"],
  ["Etc/GMT-9", "GMT+9"],
  ["Etc/GMT-10", "GMT+10"],
  ["Etc/GMT-11", "GMT+11"],
  ["Etc/GMT-12", "GMT+12"],
  ["Etc/GMT+1", "GMT-1"],
  ["Etc/GMT+2", "GMT-2"],
  ["Etc/GMT+3", "GMT-3"],
  ["Etc/GMT+4", "GMT-4"],
  ["Etc/GMT+5", "GMT-5"],
  ["Etc/GMT+6", "GMT-6"],
  ["Etc/GMT+7", "GMT-7"],
  ["Etc/GMT+8", "GMT-8"],
  ["Etc/GMT+9", "GMT-9"],
  ["Etc/GMT+10", "GMT-10"],
  ["Etc/GMT+11", "GMT-11"],
  ["Etc/GMT+12", "GMT-12"],
];

export const currencyCodes = [
  "ANG",
  "ARS",
  "AUD",
  "AZN",
  "BRL",
  "CAD",
  "CHF",
  "CLP",
  "CZK",
  "DKK",
  "EUR",
  "GBP",
  "HKD",
  "HRK",
  "HUF",
  "ILS",
  "IDR",
  "ISK",
  "JPY",
  "KRW",
  "NZD",
  "MZN",
  "PHP",
  "PKR",
  "PLN",
  "RUB",
  "SEK",
  "SGD",
  "USD",
];

export const trueOrFalse = ["True", "False"];
